namespace: platform-demo

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: sample-platform-app
    newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/sample-platform-app
    newTag: d1122dc
