namespace: platform-demo

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: sample-platform-app
    newName: 808849570426.dkr.ecr.us-east-1.amazonaws.com/sample-platform-app-rehearsal
    newTag: d1122dc
