replicaCount: null

image:
  repository: ""
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/tags: Course=pe-training,Owner=training,Environment=training,AutoDelete=true
  host: ""
  path: /
  pathType: Prefix

env:
  APP_ENV: training
  SERVICE_NAME: sample-platform-app

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

probes:
  readiness:
    path: /readyz
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 20
